spring:
  datasource:
    username: postgres
    password: psql_pass&#l2
    url: jdbc:postgresql://localhost:5432/product
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
#        ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  flyway:
#    baseline-on-migrate: true
#    enabled: true
#    baseline-description: 'init'
#    baseline-version: 1
#    user: ${spring.datasource.username}
#    password: ${spring.datasource.password}

server:
  port: 8020